if(document.querySelector(".comment-barrage")){var commentBarrageConfig={maxBarrage:GLOBAL_CONFIG.commentBarrageConfig.maxBarrage,barrageTime:GLOBAL_CONFIG.commentBarrageConfig.barrageTime,twikooUrl:GLOBAL_CONFIG.twikooEnvId,accessToken:GLOBAL_CONFIG.commentBarrageConfig.accessToken,mailMd5:GLOBAL_CONFIG.commentBarrageConfig.mailMd5,pageUrl:window.location.pathname,barrageTimer:[],barrageList:[],barrageIndex:0,dom:document.querySelector(".comment-barrage")};var commentInterval=null;var hoverOnCommentBarrage=false;document.querySelector(".comment-barrage").addEventListener("mouseenter",function(){hoverOnCommentBarrage=true});document.querySelector(".comment-barrage").addEventListener("mouseleave",function(){hoverOnCommentBarrage=false});function initCommentBarrage(){if(!commentBarrageConfig.dom)return;var e=JSON.stringify({event:"COMMENT_GET","commentBarrageConfig.accessToken":commentBarrageConfig.accessToken,url:commentBarrageConfig.pageUrl});var r=new XMLHttpRequest;r.withCredentials=true;r.addEventListener("readystatechange",function(){if(this.readyState===4&&this.responseText){commentBarrageConfig.barrageList=commentLinkFilter(JSON.parse(this.responseText).data);commentBarrageConfig.dom.innerHTML=""}});r.open("POST",commentBarrageConfig.twikooUrl);r.setRequestHeader("Content-Type","application/json");r.send(e);clearInterval(commentInterval);commentInterval=null;commentInterval=setInterval(()=>{if(commentBarrageConfig.barrageList.length&&!hoverOnCommentBarrage){popCommentBarrage(commentBarrageConfig.barrageList[commentBarrageConfig.barrageIndex]);commentBarrageConfig.barrageIndex+=1;commentBarrageConfig.barrageIndex%=commentBarrageConfig.barrageList.length}if(commentBarrageConfig.barrageTimer.length>(commentBarrageConfig.barrageList.length>commentBarrageConfig.maxBarrage?commentBarrageConfig.maxBarrage:commentBarrageConfig.barrageList.length)&&!hoverOnCommentBarrage){removeCommentBarrage(commentBarrageConfig.barrageTimer.shift())}},commentBarrageConfig.barrageTime)}function commentLinkFilter(e){e.sort((e,r)=>{return e.created-r.created});let r=[];e.forEach(e=>{r.push(...getCommentReplies(e))});return r}function getCommentReplies(e){if(e.replies){let r=[e];e.replies.forEach(e=>{r.push(...getCommentReplies(e))});return r}else{return[]}}function popCommentBarrage(e){let r=document.createElement("div");r.className="comment-barrage-item";r.innerHTML=`
          <div class="barrageHead">
            <a class="barrageTitle ${e.mailMd5===commentBarrageConfig.mailMd5?"barrageBloggerTitle":""}" href="javascript:anzhiyu.scrollTo('#post-comment')"">
              ${e.mailMd5===commentBarrageConfig.mailMd5?"博主":"热评"}
            </a>
            <div class="barrageNick">${e.nick}</div>
            <img class="nolazyload barrageAvatar" src="https://cravatar.cn/avatar/${e.mailMd5}"/>
            <a class="comment-barrage-close" href="javascript:anzhiyu.switchCommentBarrage()"><i class="anzhiyufont anzhiyu-icon-xmark"></i></a>
          </div>
          <anzhiyu class="barrageContent" onClick="window.location.hash = '${e.id}'">
            ${e.comment}
          </anzhiyu>
        `;let a=r.querySelectorAll("anzhiyu pre");a.forEach(e=>{let r=document.createElement("span");r.innerText="【代码】";e.parentNode.replaceChild(r,e)});let n=r.querySelectorAll("anzhiyu img");n.forEach(r=>{if(!r.classList.contains("tk-owo-emotion")){r.style.display="none";let e=document.createElement("span");e.innerText="【图片】";r.parentNode.replaceChild(e,r)}});commentBarrageConfig.barrageTimer.push(r);commentBarrageConfig.dom.append(r)}function removeCommentBarrage(e){e.className="comment-barrage-item out";setTimeout(()=>{if(commentBarrageConfig.dom&&commentBarrageConfig.dom.contains(e)){commentBarrageConfig.dom.removeChild(e)}},1e3)}const commentEntryCallback=e=>{const r=document.querySelector(".comment-barrage");const a=document.getElementById("post-comment");e.forEach(e=>{if(a&&r&&document.body.clientWidth>768){r.style.bottom=e.isIntersecting?`-${commentBarrageConfig.maxBarrage*200}px`:"0"}})};const observer=new IntersectionObserver(commentEntryCallback,{root:null,rootMargin:"0px",threshold:0});const postCommentTarget=document.getElementById("post-comment");if(postCommentTarget){observer.observe(postCommentTarget)}initCommentBarrage();if(localStorage.getItem("commentBarrageSwitch")!=="false"){document.querySelector(".comment-barrage").style.display="flex";document.querySelector(".menu-commentBarrage-text").textContent="关闭热评"}else{document.querySelector(".comment-barrage").style.display="none";document.querySelector(".menu-commentBarrage-text").textContent="显示热评"}document.addEventListener("pjax:send",function(){clearInterval(commentInterval)})}